name: My First
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stuff:
        description: "stuff to enter"
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world ${{ inputs.stuff }}"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: echo "my_key=my_value" >> $GITHUB_OUTPUT
        id: value-generator
      - run: echo "PREVIOUS: ${{ steps.value-generator.outputs.my_key }}"        
      - name: List Files
        run: |
          echo "Files in the repo ${{github.repository}}"
          tree


