name: My First
on: 
  push:
  workflow_dispatch:
    inputs:
      stuff:
        description: "stuff to enter"
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered by ${{ github.event_name }}"
      - run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - run: echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
      - run: echo '<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY
      - run: echo "hello world ${{ inputs.stuff }}"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: echo "my_key=my_value" >> $GITHUB_OUTPUT
        id: valuegenerator
      - run: echo "${{ steps.valuegenerator.outputs.my_key }}" 
      - name: List Files
        run: |
          echo "Files in the repo ${{github.repository}}"
          tree


